### ISSUE TITLE
Libsodium is no longer an external library in PHP 7.2

### ISSUE THREAD

**Issue by bosko-htec** [immense/php-macaroons#11]
Hi,

In version 1.0.0 php-macaroons require ext-libsodium in composer.json. This causes warnings when running `composer install` with PHP 7.2. Can you publish version 2.0 which would not require this extension as a separate entity and that would require PHP 7.2 or newer?

**Comment by cmckni3** [comment]
Does anything else need to be done? I haven't used PHP 7.2.

I removed the requirement of libsodium in master and updated the README to remove mentions of HHVM.

PRs welcome

**Comment by cmckni3** [comment]
if master works for you, I can tag as 2.0.0 so packagist can pick it up from the hooks.

**Comment by bosko-htec** [comment]
Actually, there are a few more things. PHP 7.2 includes libsodium 2.0 by default - while PHP 7.1 depended on libsodium 1.x. They changed interface a lot but your library is only slightly affected.

This are libsodium interface changes that affect your library:
- \Sodium\CRYPTO_SECRETBOX_NONCEBYTES -> \SODIUM_CRYPTO_SECRETBOX_NONCEBYTES
- \Sodium\randombytes_buf -> random_bytes
- \Sodium\crypto_secretbox -> sodium_crypto_secretbox
- \Sodium\memzero -> sodium_memzero
- \Sodium\crypto_secretbox_open -> sodium_crypto_secretbox_open

So, version 2 will need to depend upon PHP 7.2. I'll create a pull request.

**Comment by cmckni3** [comment]
Yes, I made a note in the readme about libsodium 2.x and the compatibility layer yesterday.

**Comment by bosko-htec** [comment]
Hey. We have tested your changes in production and everything works. Can you please publish them to Packagist as version 2.0.0 so we wouldn't need to reference this Git commit? Thanks in advance

**Comment by cmckni3** [comment]
I don't have access on packagist anymore.

**Comment by mhsdef** [comment]
Interested in this too. @cmbankester could we get a new version released?

**Comment by cmckni3** [comment]
Should be able to use the tag via composer since packagist picks up tags.

Add the following to your `composer.json` file or run `composer require immense/macaroons` as normal.

```
"immense/macaroons": "^2.0"
 ```
